# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Thu Sep 24 22:25:54 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(602, 606)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.lineEdit_id = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_id)
        self.label1 = QtGui.QLabel(self.configGroupBox)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label1)
        self.label = QtGui.QLabel(self.configGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.spinBox_pcsToFit = QtGui.QSpinBox(self.configGroupBox)
        self.spinBox_pcsToFit.setMinimum(1)
        self.spinBox_pcsToFit.setMaximum(99)
        self.spinBox_pcsToFit.setObjectName("spinBox_pcsToFit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_pcsToFit)
        self.label_2 = QtGui.QLabel(self.configGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_mWeight = QtGui.QDoubleSpinBox(self.configGroupBox)
        self.doubleSpinBox_mWeight.setSingleStep(0.1)
        self.doubleSpinBox_mWeight.setObjectName("doubleSpinBox_mWeight")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_mWeight)
        self.label_3 = QtGui.QLabel(self.configGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.configGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_RASIS = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_RASIS.setObjectName("lineEdit_RASIS")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_RASIS)
        self.lineEdit_LASIS = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_LASIS.setObjectName("lineEdit_LASIS")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_LASIS)
        self.comboBox_regmode = QtGui.QComboBox(self.configGroupBox)
        self.comboBox_regmode.setObjectName("comboBox_regmode")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_regmode)
        self.lineEdit_Sacral = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_Sacral.setObjectName("lineEdit_Sacral")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_Sacral)
        self.label_9 = QtGui.QLabel(self.configGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_5 = QtGui.QLabel(self.configGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_LEC = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_LEC.setObjectName("lineEdit_LEC")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_LEC)
        self.label_6 = QtGui.QLabel(self.configGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_MEC = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_MEC.setObjectName("lineEdit_MEC")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_MEC)
        self.label_7 = QtGui.QLabel(self.configGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_LM = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_LM.setObjectName("lineEdit_LM")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_LM)
        self.label_8 = QtGui.QLabel(self.configGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_MM = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_MM.setObjectName("lineEdit_MM")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit_MM)
        self.label_10 = QtGui.QLabel(self.configGroupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_kneedof = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_kneedof.setObjectName("checkBox_kneedof")
        self.horizontalLayout.addWidget(self.checkBox_kneedof)
        self.checkBox_kneecorr = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_kneecorr.setObjectName("checkBox_kneecorr")
        self.horizontalLayout.addWidget(self.checkBox_kneecorr)
        self.formLayout.setLayout(14, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_11 = QtGui.QLabel(self.configGroupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_11)
        self.checkBox_GUI = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_GUI.setText("")
        self.checkBox_GUI.setObjectName("checkBox_GUI")
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.checkBox_GUI)
        self.label_12 = QtGui.QLabel(self.configGroupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.configGroupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBox_markerRadius = QtGui.QDoubleSpinBox(self.configGroupBox)
        self.doubleSpinBox_markerRadius.setObjectName("doubleSpinBox_markerRadius")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_markerRadius)
        self.doubleSpinBox_skinPad = QtGui.QDoubleSpinBox(self.configGroupBox)
        self.doubleSpinBox_skinPad.setObjectName("doubleSpinBox_skinPad")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_skinPad)
        self.label_14 = QtGui.QLabel(self.configGroupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.comboBox_side = QtGui.QComboBox(self.configGroupBox)
        self.comboBox_side.setObjectName("comboBox_side")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_side)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_id, self.comboBox_regmode)
        Dialog.setTabOrder(self.comboBox_regmode, self.comboBox_side)
        Dialog.setTabOrder(self.comboBox_side, self.spinBox_pcsToFit)
        Dialog.setTabOrder(self.spinBox_pcsToFit, self.doubleSpinBox_mWeight)
        Dialog.setTabOrder(self.doubleSpinBox_mWeight, self.lineEdit_RASIS)
        Dialog.setTabOrder(self.lineEdit_RASIS, self.lineEdit_LASIS)
        Dialog.setTabOrder(self.lineEdit_LASIS, self.lineEdit_Sacral)
        Dialog.setTabOrder(self.lineEdit_Sacral, self.lineEdit_LEC)
        Dialog.setTabOrder(self.lineEdit_LEC, self.lineEdit_MEC)
        Dialog.setTabOrder(self.lineEdit_MEC, self.lineEdit_LM)
        Dialog.setTabOrder(self.lineEdit_LM, self.lineEdit_MM)
        Dialog.setTabOrder(self.lineEdit_MM, self.doubleSpinBox_markerRadius)
        Dialog.setTabOrder(self.doubleSpinBox_markerRadius, self.doubleSpinBox_skinPad)
        Dialog.setTabOrder(self.doubleSpinBox_skinPad, self.checkBox_kneedof)
        Dialog.setTabOrder(self.checkBox_kneedof, self.checkBox_kneecorr)
        Dialog.setTabOrder(self.checkBox_kneecorr, self.checkBox_GUI)
        Dialog.setTabOrder(self.checkBox_GUI, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure Lower Limb Registration Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "Registration Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "PCs to Fit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Mahalanobis Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "RASIS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "LASIS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Sacral:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Lateral Epicondyle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Medial Epicondyle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Lateral Malleolus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Medial Malleolus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Knee Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_kneedof.setText(QtGui.QApplication.translate("Dialog", "Abd. DOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_kneecorr.setText(QtGui.QApplication.translate("Dialog", "Abd. Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "GUI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Marker Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Skin Padding:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Side:", None, QtGui.QApplication.UnicodeUTF8))

